export const items = [
  {label: 'Apple', value: 'apple'},
  {label: 'Banana', value: 'banana', disable: true},
  {label: 'Orange', value: 'orange'},
  {label: 'Pineapple', value: 'pineapple', disable: true},
  {label: 'Mango', value: 'mango'},
  {label: 'Grapes', value: 'grapes'},
  {label: 'Blueberries', value: 'blueberries'},
  {label: 'Strawberries', value: 'strawberries'},
  {label: 'Watermelon', value: 'watermelon'},
  {label: 'Papaya', value: 'papaya'},
  {label: 'Peach', value: 'peach'},
  {label: 'Lychee', value: 'lychee'},
  {label: 'Cherry', value: 'cherry'},
  {label: 'Pomegranate', value: 'pomegranate'},
  {label: 'Guava', value: 'guava'},
  {label: 'Kiwi', value: 'kiwi'},
  {label: 'Fig', value: 'fig'},
  {label: 'Coconut', value: 'coconut'},
  {label: 'Dragonfruit', value: 'dragonfruit'},
  {label: 'Pear', value: 'pear'},
  {label: 'Plum', value: 'plum'},
  {label: 'Raspberry', value: 'raspberry'},
  {label: 'Blackberry', value: 'blackberry'},
  {label: 'Apricot', value: 'apricot'},
  {label: 'Passionfruit', value: 'passionfruit'},
  {label: 'Tangerine', value: 'tangerine'},
  {label: 'Nectarine', value: 'nectarine'},
  {label: 'Cranberry', value: 'cranberry'},
  {label: 'Mulberry', value: 'mulberry'},
  {label: 'Lemon', value: 'lemon'},
];
